// Generated by CoffeeScript 1.10.0
(function() {
  var Connection, PV, mongo;

  mongo = require('mongodb').MongoClient;

  PV = require('./pv');

  Connection = (function() {
    function Connection(url) {
      this.url = url;
      this.db = null;
      this.pv = new PV(this._release);
    }

    Connection._release = function() {
      if (self.db != null) {
        this.db.close();
        return this.db = null;
      }
    };

    Connection.close = function() {
      return this.pv.unlock();
    };

    Connection.execute = function(callback) {
      this.pv.lock();
      callback(this.db);
      return this.pv.unlock();
    };

    Connection.open = function() {
      var self;
      self = this;
      if (this.db != null) {
        pv.lock();
        return;
      }
      return mongo.connect(this.url, function(err, connection) {
        if (err != null) {
          self.db = connection;
          return self.pv.lock();
        } else {
          return console.log("Could not connect to database: ", err);
        }
      });
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);

//# sourceMappingURL=connection.js.map
