// Generated by CoffeeScript 1.10.0
(function() {
  var Avatar, api, processBody, processLine;

  Avatar = require('./avatar/model').Avatar;

  api = require('./avatar/api');

  processLine = function(value) {
    var avatar, display, login, ref, uuid;
    ref = value.split('|'), uuid = ref[0], login = ref[1], display = ref[2];
    if ((uuid == null) || (login == null)) {
      return;
    }
    if (display == null) {
      display = null;
    }
    console.log("\nProcess Line");
    console.log("uuid   : ", uuid);
    console.log("login  : ", login);
    console.log("display: ", display);
    avatar = new Avatar(uuid, login, display);
    return api.save(avatar).then(function(avatar) {
      return console.log("Successfully saved: ", avatar);
    })["catch"](function(error) {
      return console.log("Failed to save avatar: ", error);
    });
  };

  processBody = function(value) {
    var i, len, line, lines;
    if (value == null) {
      return {
        error: true,
        message: "Body was empty."
      };
    }
    lines = value.split("\n");
    console.log("\n------------------\n");
    console.log("processBody: ", lines);
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      if (line.length > 0) {
        processLine(line);
      }
    }
    return {
      error: false
    };
  };

  module.exports.processBody = processBody;

}).call(this);

//# sourceMappingURL=monitor.js.map
