// Generated by CoffeeScript 1.10.0
(function() {
  var processBody, processLine;

  processLine = function(value) {
    var display, login, ref, uuid;
    ref = value.split('|'), uuid = ref[0], login = ref[1], display = ref[2];
    if ((uuid == null) || (login == null)) {
      return;
    }
    if (display == null) {
      display = null;
    }
    console.log("\nProcess Line");
    console.log("uuid   : ", uuid);
    console.log("login  : ", login);
    return console.log("display: ", display);
  };

  processBody = function(value) {
    var i, len, line, lines, results;
    if (value == null) {
      return;
    }
    lines = value.split("\n");
    console.log("\n------------------\n");
    console.log("processBody: ", lines);
    results = [];
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      if (line.length > 0) {
        results.push(processLine(line));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  module.exports.processBody = processBody;

}).call(this);

//# sourceMappingURL=monitor.js.map
