// Generated by CoffeeScript 1.10.0
(function() {
  var PV;

  PV = (function() {
    function PV(finalCallback, initialLockValue) {
      this._lock = initialLockValue != null ? initialLockValue : {
        initialLockValue: 0
      };
      this._callback = finalCallback;
    }

    PV.prototype.lock = function() {
      return this._lock++;
    };

    PV.prototype.unlock = function() {
      this._lock--;
      if (this._lock === 0 && this._callback) {
        return this._callback();
      }
    };

    return PV;

  })();

  module.exports = PV;

}).call(this);

//# sourceMappingURL=pv.js.map
