// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, express, port, processBody, processLine, router;

  express = require('express');

  app = express();

  router = express.Router();

  bodyParser = require('body-parser');

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(bodyParser.json());

  port = process.env.PORT || 3000;

  processLine = function(value) {
    var display, login, ref, uuid;
    ref = value.split('|'), uuid = ref[0], login = ref[1], display = ref[2];
    if (display == null) {
      return;
    }
    login = (login + " ".repeat(32)).substr(0, 32);
    display = (display + " ".repeat(32)).substr(0, 32);
    return console.log(uuid, login, display);
  };

  processBody = function(value) {
    var line, lines, results;
    lines = value.split("\n");
    if (lines.length === 1 && lines[0] === '') {
      return;
    }
    results = [];
    for (line in lines) {
      results.push(processLine(line));
    }
    return results;
  };

  router.get('/', function(req, res) {
    return res.json({
      message: 'hooray! welcome to our api!'
    });
  });

  router.post('/agents/current', function(req, res) {
    processBody(req.body.value);
    return res.json({
      ack: true
    });
  });

  app.use('/api', router);

  app.listen(port);

  console.log('Magic happens on port ' + port);

}).call(this);

//# sourceMappingURL=server.js.map
