// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, express, monitor, port, router;

  express = require('express');

  bodyParser = require('body-parser');

  monitor = require('./monitor');

  app = express();

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(bodyParser.json());

  port = process.env.PORT || 3000;

  router = express.Router();

  router.get('/', function(req, res) {
    return res.json({
      message: 'hooray! welcome to our api!'
    });
  });

  router.post('/agents/current', function(req, res) {
    monitor.processBody(req.body.value);
    return res.json({
      ack: true
    });
  });

  app.use('/api', router);

  app.listen(port);

  console.log('Magic happens on port ' + port);

}).call(this);

//# sourceMappingURL=server.js.map
