// Generated by CoffeeScript 1.10.0
(function() {
  var Avatar;

  Avatar = (function() {
    function Avatar(uuid, username, displayName) {
      this.uuid = uuid != null ? uuid : null;
      this.username = username != null ? username : null;
      this.displayName = displayName != null ? displayName : null;
      this.born = null;
      this.payinfo = {
        onFile: null,
        used: null
      };
    }

    return Avatar;

  })();

  module.exports.Avatar = Avatar;

}).call(this);

//# sourceMappingURL=model.js.map
