// Generated by CoffeeScript 1.10.0
(function() {
  var Connection;

  Connection = require('./connection').Connection;

  module.exports = new Connection('mongo::localhost/grid-dev');

}).call(this);

//# sourceMappingURL=grid.js.map
